# Generated by Django 5.0 on 2023-12-13 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OGSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogs_user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OGSGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('opponent_id', models.IntegerField()),
                ('opponent_name', models.CharField(max_length=255)),
                ('width', models.PositiveSmallIntegerField(default=9)),
                ('height', models.PositiveSmallIntegerField(default=9)),
                ('handicap', models.PositiveSmallIntegerField(default=0)),
                ('komi', models.FloatField(default=6.5)),
                ('rules', models.CharField(max_length=255)),
                ('my_turn', models.BooleanField(default=True)),
                ('my_time_remaining', models.IntegerField(default=0)),
                ('opponent_time_remaining', models.IntegerField(default=0)),
                ('ogs_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogs.ogsuser')),
            ],
        ),
    ]
