# Generated by Django 5.0 on 2023-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogsuser',
            name='token_expiry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
