# Generated by Django 5.0 on 2023-12-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0002_ogsuser_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogsgame',
            name='moves',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
