# Generated by Django 5.0 on 2023-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DGSGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255)),
                ('sgf', models.FileField(upload_to='sgf')),
                ('status', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished')], default='running', max_length=255)),
                ('rated', models.BooleanField(default=True)),
                ('size', models.SmallIntegerField(default=9)),
                ('komi', models.FloatField(default=6.5)),
                ('ruleset', models.CharField(max_length=255)),
                ('is_rated', models.BooleanField(default=True)),
                ('opponent_userid', models.CharField(max_length=255)),
                ('opponent_name', models.CharField(max_length=255)),
                ('moves', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DGSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, unique=True)),
                ('cookie_sessioncode', models.TextField(blank=True, null=True)),
                ('cookie_handle', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
