# Generated by Django 5.0 on 2023-12-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0003_dgsgame_handicap_dgsgame_my_time_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgsgame',
            name='my_turn',
            field=models.BooleanField(default=True),
        ),
    ]
